default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: qwerty

development:
  <<: *default
  database: logging_middleware_app_development

test:
  <<: *default
  database: logging_middleware_app_test

production:
  <<: *default
  database: myapp_production
 
